/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as JogadoresRouteImport } from './routes/jogadores'
import { Route as NovaPartidaRouteImport } from './routes/nova-partida'
import { Route as PartidaIdRouteImport } from './routes/partida.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const JogadoresRoute = JogadoresRouteImport.update({
  id: '/jogadores',
  path: '/jogadores',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaPartidaRoute = NovaPartidaRouteImport.update({
  id: '/nova-partida',
  path: '/nova-partida',
  getParentRoute: () => rootRouteImport,
} as any)
const PartidaIdRoute = PartidaIdRouteImport.update({
  id: '/partida/$id',
  path: '/partida/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/jogadores': typeof JogadoresRoute
  '/nova-partida': typeof NovaPartidaRoute
  '/partida/$id': typeof PartidaIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/jogadores': typeof JogadoresRoute
  '/nova-partida': typeof NovaPartidaRoute
  '/partida/$id': typeof PartidaIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/jogadores': typeof JogadoresRoute
  '/nova-partida': typeof NovaPartidaRoute
  '/partida/$id': typeof PartidaIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/jogadores' | '/nova-partida' | '/partida/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/jogadores' | '/nova-partida' | '/partida/$id'
  id: '__root__' | '/' | '/jogadores' | '/nova-partida' | '/partida/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  JogadoresRoute: typeof JogadoresRoute
  NovaPartidaRoute: typeof NovaPartidaRoute
  PartidaIdRoute: typeof PartidaIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogadores': {
      id: '/jogadores'
      path: '/jogadores'
      fullPath: '/jogadores'
      preLoaderRoute: typeof JogadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-partida': {
      id: '/nova-partida'
      path: '/nova-partida'
      fullPath: '/nova-partida'
      preLoaderRoute: typeof NovaPartidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partida/$id': {
      id: '/partida/$id'
      path: '/partida/$id'
      fullPath: '/partida/$id'
      preLoaderRoute: typeof PartidaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  JogadoresRoute: JogadoresRoute,
  NovaPartidaRoute: NovaPartidaRoute,
  PartidaIdRoute: PartidaIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
